# Generated by Django 4.0.4 on 2022-05-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pluscal', '0002_delete_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='calc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_1', models.IntegerField()),
                ('number_2', models.IntegerField()),
            ],
        ),
    ]
